namespace m8.chess.MoveGeneration.sliders.magics;

/// <summary>
///  Result of the FindMagic method.
/// </summary>
public struct BlackMagicConstants
{
    /// <summary>
    ///  Constructor
    /// </summary>
    public BlackMagicConstants(ulong magic, int minIndex, int maxIndex)
    {
        Magic = magic;
        MinIndex = minIndex;
        MaxIndex = maxIndex;
    }

    /// <summary>
    ///  Magic number
    /// </summary>
    public ulong Magic { get; set; }

    /// <summary>
    ///  Minimum index generated by this magic.
    /// </summary>
    public int MinIndex { get; set; }

    /// <summary>
    ///  Minimum index generated by this magic.
    /// </summary>
    public int MaxIndex { get; set; }

    /// <summary>
    ///  Returns the range necessary in the attack table
    /// </summary>
    public int AttackTableRange { get => MaxIndex - MinIndex + 1; }

    /// <summary>
    ///  Returns a string representing a call to new that can recreate the instance.
    /// </summary>
    public override string ToString()
    {
        return $"new BlackMagicConstants(0x{Magic:x16}ul, {MinIndex,4}, {MaxIndex,4})";
    }
}
